name: test
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        apiLevel:
          - 34
        target:
          - test-app-legacy
          - test-app-styled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      # https://github.com/sdkman/sdkman-action/issues/16
      - uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
      - uses: android-actions/setup-android@v3
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiLevel}}
          script: make ${{ matrix.target }}
